# Site settings
title: The Code of Klaathulhu
email: fw222ek@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  The landing page for software development student Klaathulhu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://klaathulhu.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  klaathulhu
facebook_username: fredrik.wallstedt
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/posts/page:num/"

# Build settings
markdown: kramdown
